### ISSUE TITLE
Solicit advice from MIMIC team

### ISSUE THREAD

**Issue by n-s-f** [n-s-f/mimic-etl#3]
@alistairewj 

I'm putting some of the tools I've developed to work on MIMIC data together in this library.  The basic idea can be found in the [readme](https://github.com/n-s-f/mimic-etl/blob/master/README.md), and an early demo can be found in [here](https://github.com/n-s-f/mimic-etl/blob/master/examples/etl_demo.ipynb).

The main goal is to make it easy to create, share and reproduce data extractions from MIMIC. In particular, I hope to get to a situation where all that's needed is to share a python script detailing the Events and Tasks required, where all relevant SQL scripts and Event definitions will be contained in this library.

If you have any thoughts on the direction this can take to become useful to the community, they would be much appreciated.

**Comment by alistairewj** [comment]
It's an interesting project and thanks for asking me for my opinion.

One of the issues that we run into is a lack of SQL knowledge - for example, there are a lot of people who are proficient at python but don't know how to read or write SQL queries. Since a lot of our concepts are dependent on these queries, they end up struggling against syntax rather than making progress on their project. So, with that in mind, having an abstraction layer that lets them access the data with only python would be quite useful. However, from my naive view, I suppose the repository isn't quite at that stage, though if that's a goal I think it's laudable.

I'm also not sure what the down-stream use of the data is. Have you considered how the data extraction will integrate with other packages like statsmodels, scikit-learn, tensorflow, pytorch, etc?

Finally, I'd like to highlight that we are in the process of [moving MIMIC into the OMOP Common Data Model](https://github.com/MIT-LCP/mimic-omop) - perhaps it's worth focusing your data extraction to be based on that schema. Then, it would be transferable to other hospital datasets that use that format. Currently most of the tools that use OMOP are in R, so building up a python toolkit would be welcome!

**Comment by n-s-f** [comment]
Thanks! This is all very useful information.

Yes, one of the goals is that eventually people would not have to write SQL to extract data from the mimic database, but I agree that this is a long way off. Another goal is to make it easy to share data extractions as short scripts, and to make the data extraction piece of the project easier.  Even before it's possible to entirely avoid writing SQL, it will be possible to extract data with mostly built in templates.

With regard to downstream use, the library leaves that up to the user; it just makes the data available in python. I've used earlier versions of this code to build models using scikit-learn, tensorflow, pytorch, and other custom code.

Thanks for pointing to the OMOP CDM! I think the structure of this library would be the same across data models, so I might add another set of templates alongside the mimic templates.
